name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: piranna/jekyll-social@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        social: ${{ secrets.social }}
        user_access_token: ${{ secrets.user_access_token }}
